# Generated by Django 2.2.9 on 2020-01-26 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auteur_genre_langue_livre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livre',
            old_name='isbne',
            new_name='isbn',
        ),
        migrations.RenameField(
            model_name='livre',
            old_name='titree',
            new_name='titre',
        ),
        migrations.RemoveField(
            model_name='livre',
            name='id_auteur',
        ),
        migrations.RemoveField(
            model_name='livre',
            name='id_genre',
        ),
        migrations.RemoveField(
            model_name='livre',
            name='id_langue',
        ),
        migrations.AddField(
            model_name='livre',
            name='auteur_nom',
            field=models.CharField(default='unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='livre',
            name='genre_nom',
            field=models.CharField(default='unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='livre',
            name='langue_nom',
            field=models.CharField(default='unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='livre',
            name='quantite',
            field=models.IntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='Auteur',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
        migrations.DeleteModel(
            name='Langue',
        ),
    ]
