# Generated by Django 2.2.9 on 2020-01-26 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200126_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livre',
            name='date_achat',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='livre',
            name='date_entree',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='livre',
            name='date_lecture',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='livre',
            name='date_publication',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='livre',
            name='isbn',
            field=models.CharField(default='unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='livre',
            name='nb_pages',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='livre',
            name='note',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='livre',
            name='prix',
            field=models.FloatField(blank=True),
        ),
    ]
