# Generated by Django 2.2.9 on 2020-01-26 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200126_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livre',
            name='date_publication',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
