# Generated by Django 2.2.9 on 2020-01-26 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200126_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livre',
            name='date_achat',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='livre',
            name='date_entree',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='livre',
            name='date_lecture',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='livre',
            name='nb_pages',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='livre',
            name='note',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='livre',
            name='prix',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
