# Generated by Django 2.2.9 on 2020-01-26 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20200126_1817'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageLivre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, help_text='(optional) room image field', null=True, upload_to='')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='(automatic) created date')),
                ('alt', models.CharField(default='blank', help_text='(required) SEO for images in order to provide accessibility for the visually impaired', max_length=120)),
                ('location', models.ForeignKey(help_text='(automatic) room model linkage', on_delete=django.db.models.deletion.PROTECT, related_name='room_image', to='core.Livre')),
            ],
        ),
    ]
