# Generated by Django 2.2.9 on 2020-01-26 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20200126_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagelivre',
            name='livre',
            field=models.ForeignKey(help_text='(automatic) room model linkage', on_delete=django.db.models.deletion.CASCADE, related_name='room_image', to='core.Livre'),
        ),
    ]
