# Generated by Django 2.2.9 on 2020-01-26 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20200126_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livre',
            name='auteur_nom',
            field=models.CharField(default='unknown', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='livre',
            name='genre_nom',
            field=models.CharField(default='unknown', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='livre',
            name='isbn',
            field=models.CharField(default='unknown', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='livre',
            name='langue_nom',
            field=models.CharField(default='unknown', max_length=50, null=True),
        ),
    ]
