# Generated by Django 2.2.9 on 2020-02-15 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20200126_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='livre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Livre'),
        ),
    ]
