# Generated by Django 2.2.9 on 2020-02-15 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_orderitem_livre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='item',
        ),
    ]
