# Generated by Django 2.2.9 on 2020-02-15 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_orderitem_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='item',
        ),
    ]
