# Generated by Django 2.2 on 2020-03-23 13:54

from django.db import migrations
from django.contrib.postgres.operations import UnaccentExtension


class Migration(migrations.Migration):

    dependencies = [("core", "0019_auto_20200322_0914")]

    operations = [UnaccentExtension()]
