# Generated by Django 2.2 on 2020-04-07 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20200323_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='livre',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
