# Generated by Django 2.2 on 2020-04-10 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_livre_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livre',
            name='date_achat',
        ),
        migrations.RemoveField(
            model_name='livre',
            name='date_entree',
        ),
        migrations.RemoveField(
            model_name='livre',
            name='date_lecture',
        ),
        migrations.RemoveField(
            model_name='livre',
            name='quantite',
        ),
        migrations.CreateModel(
            name='LivreItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_achat', models.DateTimeField(blank=True, null=True)),
                ('date_lecture', models.DateTimeField(blank=True, null=True)),
                ('date_entree', models.DateTimeField(blank=True, null=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livre_item', to='core.Livre')),
            ],
        ),
    ]
