# Generated by Django 2.2 on 2020-04-10 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20200410_0714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livreitem',
            name='auteur',
        ),
        migrations.AddField(
            model_name='livreitem',
            name='quantity',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='quantity', to='core.Livre'),
        ),
    ]
