# Generated by Django 2.2 on 2020-04-10 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20200410_0729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagelivre',
            name='livre',
            field=models.ForeignKey(help_text='(automatic) room model linkage', on_delete=django.db.models.deletion.CASCADE, related_name='livre_name', to='core.Livre'),
        ),
        migrations.AlterField(
            model_name='livre',
            name='description',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='livreitem',
            name='quantity',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='book_quantity', to='core.Livre'),
        ),
    ]
