# Generated by Django 2.2 on 2020-04-10 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20200410_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livre',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
