# Generated by Django 2.2 on 2020-04-11 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20200411_1440'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livreitem',
            old_name='quantity',
            new_name='livre',
        ),
    ]
