# Generated by Django 2.2 on 2020-04-11 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20200411_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='livre',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
