# Generated by Django 2.2 on 2020-04-18 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_imagelivre_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='livre',
            name='picture',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
