# Generated by Django 2.2 on 2020-04-19 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_livre_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livre',
            name='isbn',
            field=models.CharField(default='unknown', max_length=50, unique=True),
        ),
    ]
