# Generated by Django 2.2 on 2020-04-19 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_auto_20200419_0854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livre',
            name='picture',
        ),
        migrations.AlterField(
            model_name='imageauteur',
            name='image',
            field=models.FileField(blank=True, help_text='(optional) author image field', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='imagelivre',
            name='image',
            field=models.FileField(blank=True, help_text='(optional) book image field', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='imagelivre',
            name='livre',
            field=models.ForeignKey(help_text='(automatic) book model linkage', on_delete=django.db.models.deletion.CASCADE, related_name='livre_name', to='core.Livre'),
        ),
    ]
