# Generated by Django 3.0.5 on 2022-11-27 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_auto_20200423_0800'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='livre',
            options={'ordering': ('-created',)},
        ),
        migrations.AlterModelOptions(
            name='livreitem',
            options={'ordering': ('-created',)},
        ),
    ]
